import * as DataTypes from '../../../astrofy-admin/src/types/types';

export const mockGetItems: DataTypes.ItemOutputSchema[] = [
	{
		id: 1,
		manufacturer: "Xiaomi",
		model: "Mi Notebook Pro",
		category: DataTypes.ItemType.LAPTOP,
		description: "Xiaomi Mi Notebook Pro 15 (2020) is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Xiaomi Mi Notebook Pro 15 (2020) packs 512GB of SSD storage. Graphics are powered by Nvidia GeForce MX350.",
		quantity: 12,
		CPU: "Intel Core i5 8250U",
		GPU: "Nvidia GeForce MX150",
		RAM: 8,
		diagonal: 15.6,
		driveCapacity: 256,
		batteryCapacity: 8000,
		cost: 2000
	} as DataTypes.ItemOutputSchema,
	{
		id: 2,
		manufacturer: "Xiaomi",
		model: "Mi Notebook Pro",
		category: DataTypes.ItemType.LAPTOP,
		description: "Xiaomi Mi Notebook Pro 15 (2020) is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Xiaomi Mi Notebook Pro 15 (2020) packs 512GB of SSD storage. Graphics are powered by Nvidia GeForce MX350.",
		quantity: 12,
		CPU: "Intel Core i5 8250U",
		GPU: "Nvidia GeForce MX150",
		RAM: 8,
		diagonal: 15.6,
		driveCapacity: 256,
		batteryCapacity: 8000,
		cost: 2000
	} as DataTypes.ItemOutputSchema,
	{
		id: 3,
		manufacturer: "Xiaomi",
		model: "Mi Notebook Pro",
		category: DataTypes.ItemType.LAPTOP,
		description: "Xiaomi Mi Notebook Pro 15 (2020) is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Xiaomi Mi Notebook Pro 15 (2020) packs 512GB of SSD storage. Graphics are powered by Nvidia GeForce MX350.",
		quantity: 12,
		CPU: "Intel Core i5 8250U",
		GPU: "Nvidia GeForce MX150",
		RAM: 8,
		diagonal: 15.6,
		driveCapacity: 256,
		batteryCapacity: 8000,
		cost: 2000
	} as DataTypes.ItemOutputSchema,
	{
		id: 4,
		manufacturer: "Xiaomi",
		model: "Mi Notebook Pro",
		category: DataTypes.ItemType.LAPTOP,
		description: "Xiaomi Mi Notebook Pro 15 (2020) is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Xiaomi Mi Notebook Pro 15 (2020) packs 512GB of SSD storage. Graphics are powered by Nvidia GeForce MX350.",
		quantity: 12,
		CPU: "Intel Core i5 8250U",
		GPU: "Nvidia GeForce MX150",
		RAM: 8,
		diagonal: 15.6,
		driveCapacity: 256,
		batteryCapacity: 8000,
		cost: 2000
	} as DataTypes.ItemOutputSchema,
	{
		id: 5,
		manufacturer: "Xiaomi",
		model: "Mi Notebook Pro",
		category: DataTypes.ItemType.LAPTOP,
		description: "Xiaomi Mi Notebook Pro 15 (2020) is a Windows 10 Home laptop with a 15.60-inch display that has a resolution of 1920x1080 pixels. It is powered by a Core i5 processor and it comes with 8GB of RAM. The Xiaomi Mi Notebook Pro 15 (2020) packs 512GB of SSD storage. Graphics are powered by Nvidia GeForce MX350.",
		quantity: 12,
		CPU: "Intel Core i5 8250U",
		GPU: "Nvidia GeForce MX150",
		RAM: 8,
		diagonal: 15.6,
		driveCapacity: 256,
		batteryCapacity: 8000,
		cost: 2000
	} as DataTypes.ItemOutputSchema,
]
